# ==========================
# Server configuration
# ==========================

# ==========================
# SQL Server (old config - commented)
# ==========================
# spring:
#   datasource:
#     url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=izumiya
#     username: sa
#     password: 12345
#     driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#   jpa:
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.SQLServerDialect
#         format_sql: true
#     hibernate:
#       ddl-auto: update
#     show-sql: false

# ==========================
# PostgreSQL (active config)
# ==========================

spring:

  datasource:
    url: jdbc:postgresql://${{ secrets.IP }}/trouni?cloudSqlInstance=trouni-473306:asia-east1:trouni-db&socketFactory=com.google.cloud.sql.postgres.SocketFactory
    username: ${{ secrets.DB_USERNAME }}
    password: ${{ secrets.DB_PASSWORD }}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: izumiyakoi686@gmail.com
    password: jjss izns pwcm liuv
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

# ==========================
# JWT
# ==========================
jwt:
  signerKey: wFRihVlJq7afNGtN5lT1DQ3FQ7akvsXHSLC//3kYHZoI1wHhmndyQPySyPUYxzT/

# ==========================
# PayPal
# ==========================
paypal:
  client-id: Ab6PpbktTWAl6wjVj_Tx1lsNsiN_Vw6VSF2421fu4pKII1eT-ft9GH9lR8ZNG-Ipvw7axpWL2D-t7ffg
  client-secret: EE8LlzGtg4gMnfPT0Uc6D3XNvdTFMJMqpLoDNOk69eZTM3Xm9N8Ysj0oML2s5ioPRbxpDgEF1Ph4lwsr
  mode: sandbox
